### ISSUE TITLE
recommend to use spaces rather than tabs for indentation

### ISSUE THREAD

**Issue by typd** [conndots/python-design-patterns#1]
https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces

**Comment by conndots** [comment]
Ok. I haven't check those codes for PEP-8 conventions.

**Comment by typd** [comment]
pylint is helpful http://www.pylint.org/
I use it as a plugin for vim

**Comment by conndots** [comment]
I found the plugin [pylint-mode](https://github.com/vim-scripts/pylint-mode) makes gVim crash when open a file in Windows. Wait for my MBP :)

**Comment by conndots** [comment]
Ok. Now vim looks like an old-fashioned IDE.
![vim.png](http://7xiub6.com1.z0.glb.clouddn.com/github/tmpvim.png)

**Comment by typd** [comment]
Awsome
